name: Evolutions
version: 1.1.9
main: me.natecb13.plugin.Evolutions
api-version: 1.13
commands:
  evolutions:
    description: Base command for the Evolutions plugin. Use /evo for more information!
    aliases: [evo]
permissions:
  evolutions.admin:
    default: op
softdepend: [PlaceholderAPI]
